import type { EnemyProfile } from "../types";
import { PUTREFACTIVE_LAIR_PROFILE } from "./lairPutrefactive";
import { BOSS_BLOOD_CHIEF_PROFILE } from "./bossBloodChief";
import { LAIR_INSECT_HIVE_PROFILE } from "./lairs/insectHive";
import { LAIR_BEAST_CAVE_PROFILE } from "./lairs/beastCave";
import { LAIR_SHADOW_GATE_PROFILE } from "./lairs/shadowGate";
import { LAIR_CRYSTAL_VEIN_PROFILE } from "./lairs/crystalVein";
import { LAIR_CORRUPTED_TEMPLE_PROFILE } from "./lairs/corruptedTemple";
import { BOSS_DEMON_COMMANDER_PROFILE } from "./bosses/demonCommander";
import { BOSS_NIGHTMARE_LORD_PROFILE } from "./bosses/nightmareLord";
import { BOSS_ELDER_DEMON_PROFILE } from "./bosses/elderDemon";
import { BOSS_INFERNAL_DEMON_PROFILE } from "./bosses/infernalDemon";
import { BOSS_FEY_REBEL_KING_PROFILE } from "./bosses/feyRebelKing";
import { BOSS_BEAST_KING_PROFILE } from "./bosses/beastKing";

const ALL_PROFILES: EnemyProfile[] = [
  PUTREFACTIVE_LAIR_PROFILE,
  BOSS_BLOOD_CHIEF_PROFILE,
  LAIR_INSECT_HIVE_PROFILE,
  LAIR_BEAST_CAVE_PROFILE,
  LAIR_SHADOW_GATE_PROFILE,
  LAIR_CRYSTAL_VEIN_PROFILE,
  LAIR_CORRUPTED_TEMPLE_PROFILE,
  BOSS_DEMON_COMMANDER_PROFILE,
  BOSS_NIGHTMARE_LORD_PROFILE,
  BOSS_ELDER_DEMON_PROFILE,
  BOSS_INFERNAL_DEMON_PROFILE,
  BOSS_FEY_REBEL_KING_PROFILE,
  BOSS_BEAST_KING_PROFILE,
];

export const ENEMY_PROFILES: Record<string, EnemyProfile> = Object.fromEntries(ALL_PROFILES.map((p) => [p.id, p]));

export {
  PUTREFACTIVE_LAIR_PROFILE,
  BOSS_BLOOD_CHIEF_PROFILE,
  LAIR_INSECT_HIVE_PROFILE,
  LAIR_BEAST_CAVE_PROFILE,
  LAIR_SHADOW_GATE_PROFILE,
  LAIR_CRYSTAL_VEIN_PROFILE,
  LAIR_CORRUPTED_TEMPLE_PROFILE,
  BOSS_DEMON_COMMANDER_PROFILE,
  BOSS_NIGHTMARE_LORD_PROFILE,
  BOSS_ELDER_DEMON_PROFILE,
  BOSS_INFERNAL_DEMON_PROFILE,
  BOSS_FEY_REBEL_KING_PROFILE,
  BOSS_BEAST_KING_PROFILE,
};
